### ISSUE TITLE
dependency err on install

### ISSUE THREAD

**Issue by Cortexelus** [drawnepicenter/leximaven#21]
upon `sudo npm install -g leximaven`, ubuntu linux

```
npm ERR! Error: No compatible version found: circuit-breaker-js@'Schibsted-Tech-Polska/circuit-breaker-js#v0.0.2'
npm ERR! Valid install targets:
npm ERR! ["0.0.0","0.0.1"]
npm ERR!     at installTargetsError (/usr/share/npm/lib/cache.js:719:10)
npm ERR!     at /usr/share/npm/lib/cache.js:638:10
npm ERR!     at saved (/usr/share/npm/node_modules/npm-registry-client/lib/get.js:142:7)
npm ERR!     at /usr/lib/nodejs/graceful-fs/polyfills.js:133:7
npm ERR!     at Object.oncomplete (fs.js:107:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.13.0-74-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "leximaven"
npm ERR! cwd /home/ubuntu/leximaven
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /home/ubuntu/leximaven/npm-debug.log
npm ERR! not ok code 0
```

**Comment by drawnepicenter** [comment]
Looks like it's a dependency issue with good-guy-http's lib. Back in October it was changed from version 0.01 from npm repo to 0.0.2 with an installation from Github. good-guy-http was also recently updated to 1.8.0. Make sure git is installed on your machine, clone the repo, and do an `npm install`. If it works, then just do npm install -g and it should work. Let me know how it works!
